env:
  es6: true
  node: true
  mocha: true
extends: 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
  '@typescript-eslint/indent':
    - error
    - 2
  ' @typescript-eslint/no-explicit-any':
    - warning